export enum ZarinpalProvidersKey {
  LOGGER = 'ZP_LOGGER',
  MERCHANT_ID = 'ZP_MERCHANT_ID',
  SOAP_CLIENT = 'ZP_SOAP_CLIENT',
  CALLBACK_URL = 'ZP_CALLBACK_URL',
  SANDBOX_MODE = 'ZP_SANDBOX_MODE',

  TRANSACTION_OPEN_URL = 'ZP_TRANSACTION_OPEN_URL',
  TRANSACTION_VERIFY_URL = 'ZP_TRANSACTION_VERIFY_URL',
  TRANSACTION_START_URL = 'ZP_TRANSACTION_START_URL',
}
